config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users

  # resources :staff_categories, only: [:index, :create, :update, :delete, :destroy]
  # resources :staff_departments, only: [:index, :create, :update, :delete, :destroy]

    #School Resouces
    resource :school_infos, only: [:new, :show, :edit, :update, :create, :delete, :destroy], path_names: { new: 'add'}
    resources :gradelevels, :programmes, :classrooms, :periods, :badges

    #Staff Resources
    resources :staff_departments
    resources :staffs do
      member do
        get :contacts
        get :add_contact
        get :edit_contact
        put :update_contact
      end
      collection do
        get :manage
        # put :action
        # post :action
        # delete :action
      end
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :programme
  belongs_to :gradelevel

  validates_presence_of :name, :gradelevel_id, :programme_id
  def full_name()
    self.gradelevel.level.to_s + self.name
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord

  validates_presence_of :name, :capacity
end

app/models/gradelevel.rb
class Gradelevel < ApplicationRecord

end

app/models/period.rb
class Period < ApplicationRecord

  def duration
    
  end
end

app/models/programme.rb
class Programme < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/school_info.rb
class SchoolInfo < ApplicationRecord
  mount_uploader :logo, PhotoUploader

  validates_presence_of :name, :code
end

app/models/staff.rb
class Staff < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  belongs_to :staff_department
  has_many :staff_contacts
  has_many :staff_addresses

  accepts_nested_attributes_for :staff_addresses
  accepts_nested_attributes_for :staff_contacts
  # Categories = %w[Academic Non-Academic].freeze

  extend FriendlyId
    friendly_id :first_name, use: :slugged

  def should_generate_new_friendly_id?
    first_name_changed?
  end
  validates_presence_of :first_name, :last_name, :gender, :joining_date, :staff_department_id

  def full_name(title=nil)
    self.title + ' ' + self.last_name + ' ' + self.first_name
  end
end

app/models/staff_address.rb
class StaffAddress < ApplicationRecord
  belongs_to :staff
end

app/models/staff_contact.rb
class StaffContact < ApplicationRecord
  belongs_to :staff
end

app/models/staff_department.rb
class StaffDepartment < ApplicationRecord
  belongs_to :staff_category
  has_many :staffs

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_many :staffs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

	 EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\z/i
	 validates_uniqueness_of :email
	 validates_presence_of :email, :password, :role
	 validates_format_of :email, with: EMAIL_REGEX


  def super?
   self.role.name == "super administrator"
  end

  def admin?
   self.role.name == "administrator"
  end

  def teacher?
   self.role.name == "teacher"
  end

  def student?
   self.role.name == "student"
  end

  def guardian?
   self.role.name == "guardian"
  end
end

app/controllers/programmes_controller.rb
class ProgrammesController < ApplicationController
  before_action :set_programme, only: [:show, :edit, :update, :destroy]

  def index
    @programmes = Programme.all
    @programme = Programme.new
  end

  def show
  end

  def new
    @programme = Programme.new
  end

  def edit
  end

  def create
    @programme = Programme.new(programme_params)
    @programme.created_by = current_user.email

    respond_to do |format|
      if @programme.save
        format.html { redirect_to @programme, notice: 'Programme was successfully created.' }
        format.json { render :show, status: :created, location: @programme }
        format.js
      else
        format.html { render :new }
        format.json { render json: @programme.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      @programme.updated_by = current_user.email
      if @programme.update(programme_params)
        format.html { redirect_to @programme, notice: 'Programme was successfully updated.' }
        format.json { render :show, status: :ok, location: @programme }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @programme.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @programme.destroy
    respond_to do |format|
      format.html { redirect_to programmes_url, notice: 'Programme was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programme
      @programme = Programme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def programme_params
      params.require(:programme).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
   render(partial: "application/error_messages", locals: {object: object})
  end

  def alert_messages(alert)
   render(partial: "application/alert_messages", locals: {msg: alert})
  end

 def notice_messages(notice)
   render(partial: "application/alert_messages", locals: {msg: notice})
 end

 def user_menu(user)
   render(partial: "layouts/menu", locals: {user: user})
 end

 def sortable(column, title=nil)
   title ||= column.titleize
   css_classes = column == sort_column ? "current-column #{sort_direction}" : nil
   direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
   link_to title, params.permit(:sort, :direction, :page, :k).merge(:sort => column, :direction => direction, :page => nil), {class: "#{css_classes}"}
 end



end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map {|day| content_tag :th, day}.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map {|day| day_cell(day)}.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/gradelevels_helper.rb
module GradelevelsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/programmes/_form.html.erb
<%= simple_form_for(@programme) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/programmes/_modal-form.html.erb
<%= simple_form_for(@programme, html: {class: "form-horizontal"}, remote: true) do |f| %>
  <%= f.error_notification %>
  <div class="modal fade" id="newProgramme" tabindex="-1" role="dialog" aria-labelledby="programmeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="programmeModalLabel"><i class="fa fa-plus"> Programme </i></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <br>
          <%= f.input :name, input_html: {class: "programme_name"}, label: false, placeholder: "Name" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
          <%= f.button :submit, "Create", class: "btn btn-primary btn-sm" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/programmes/_programme.html.erb
<tr id="programmeRow_<%= programme.id %>">
  <td><%= programme.name %></td>
  <td>
    <div class="button-group" role="group" aria-label="Actions">
      <button type="button" name="updateprogramme" data-toggle= "modal" data-target="#updateprogramme_<%= programme.id %>" class="btn btn-warning btn-sm"><i class="fa fa-pencil"></i></button>
      <%= link_to "#{content_tag(:i, '', :class => ("fa fa-trash"))}".html_safe, programme_path(programme), method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger btn-sm", remote: true%>
    </div>

    <%= simple_form_for(programme, html: {class: "form-horizontal"}, remote: true) do |f| %>
      <%= f.error_notification %>
      <div class="modal fade" id="updateprogramme_<%= programme.id %>" tabindex="-1" role="dialog" aria-labelledby="programmeModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="programmeModalLabel"><i class="fa fa-pencil"> Programme</i></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <br>
              <%= f.input :name %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
              <%= f.button :submit, "Update", class: "btn btn-primary btn-sm" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </td>
</tr>

app/views/programmes/create.js.erb
$('#newProgramme').modal('toggle');
$('.programme_name').val('');
$('#progTbdy').append('<%= j render @programme %>');

app/views/programmes/destroy.js.erb
$('#programmeRow_<%= @programme.id %>').fadeOut(500, function () {
  $(this).remove();
});

app/views/programmes/edit.html.erb
<h1>Editing Programme</h1>

<%= render 'form', programme: @programme %>

<%= link_to 'Show', @programme %> |
<%= link_to 'Back', programmes_path %>

app/views/programmes/index.html.erb
<%= provide(:page_title, "Programmes") %>

<table class="table table-sm table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody id="progTbdy">
    <%= render @programmes %>
  </tbody>
</table>
<button type="button" name="newProgramme" data-toggle= "modal" data-target="#newProgramme" class="btn btn-sm btn-primary float-right"><i class="fa fa-plus"></i></button>

<%= render(:partial => 'modal-form', :locals => {programme: @programme}) %>

app/views/programmes/new.html.erb
<h1>New Programme</h1>

<%= render 'form', programme: @programme %>

<%= link_to 'Back', programmes_path %>

app/views/programmes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @programme.name %>
</p>

<%= link_to 'Edit', edit_programme_path(@programme) %> |
<%= link_to 'Back', programmes_path %>

app/views/programmes/update.js.erb
$('#updateprogramme_<%= @programme.id%>').modal('toggle');
$('#programmeRow_<%= @programme.id %>').fadeOut(500, function () {
  $(this).remove();
  $('#progTbdy').append('<%= j render @programme %>');
});