config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users

  # resources :staff_categories, only: [:index, :create, :update, :delete, :destroy]
  # resources :staff_departments, only: [:index, :create, :update, :delete, :destroy]

    #School Resouces
    resource :school_infos, only: [:new, :show, :edit, :update, :create, :delete, :destroy], path_names: { new: 'add'}
    resources :gradelevels, :programmes, :classrooms, :periods, :badges

    #Staff Resources
    resources :staff_departments
    resources :staffs do
      member do
        get :contacts
        get :add_contact
        get :edit_contact
        put :update_contact
      end
      collection do
        get :manage
        # put :action
        # post :action
        # delete :action
      end
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :programme
  belongs_to :gradelevel

  validates_presence_of :name, :gradelevel_id, :programme_id
  def full_name()
    self.gradelevel.level.to_s + self.name
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord

  validates_presence_of :name, :capacity
end

app/models/gradelevel.rb
class Gradelevel < ApplicationRecord

end

app/models/period.rb
class Period < ApplicationRecord

  def duration
    
  end
end

app/models/programme.rb
class Programme < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/school_info.rb
class SchoolInfo < ApplicationRecord
  mount_uploader :logo, PhotoUploader

  validates_presence_of :name, :code
end

app/models/staff.rb
class Staff < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  belongs_to :staff_department
  has_many :staff_contacts
  has_many :staff_addresses

  accepts_nested_attributes_for :staff_addresses
  accepts_nested_attributes_for :staff_contacts
  # Categories = %w[Academic Non-Academic].freeze

  extend FriendlyId
    friendly_id :first_name, use: :slugged

  def should_generate_new_friendly_id?
    first_name_changed?
  end
  validates_presence_of :first_name, :last_name, :gender, :joining_date, :staff_department_id

  def full_name(title=nil)
    self.title + ' ' + self.last_name + ' ' + self.first_name
  end
end

app/models/staff_address.rb
class StaffAddress < ApplicationRecord
  belongs_to :staff
end

app/models/staff_contact.rb
class StaffContact < ApplicationRecord
  belongs_to :staff
end

app/models/staff_department.rb
class StaffDepartment < ApplicationRecord
  belongs_to :staff_category
  has_many :staffs

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_many :staffs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

	 EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\z/i
	 validates_uniqueness_of :email
	 validates_presence_of :email, :password, :role
	 validates_format_of :email, with: EMAIL_REGEX


  def super?
   self.role.name == "super administrator"
  end

  def admin?
   self.role.name == "administrator"
  end

  def teacher?
   self.role.name == "teacher"
  end

  def student?
   self.role.name == "student"
  end

  def guardian?
   self.role.name == "guardian"
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create

    respond_to do |format|
        @badge = Badge.new(badge_params)
        @badge.created_by = current_user.email
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @badge.updated_by = current_user.email
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:name, :programme_id, :gradelevel_id, :start_date, :end_date, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
   render(partial: "application/error_messages", locals: {object: object})
  end

  def alert_messages(alert)
   render(partial: "application/alert_messages", locals: {msg: alert})
  end

 def notice_messages(notice)
   render(partial: "application/alert_messages", locals: {msg: notice})
 end

 def user_menu(user)
   render(partial: "layouts/menu", locals: {user: user})
 end

 def sortable(column, title=nil)
   title ||= column.titleize
   css_classes = column == sort_column ? "current-column #{sort_direction}" : nil
   direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
   link_to title, params.permit(:sort, :direction, :page, :k).merge(:sort => column, :direction => direction, :page => nil), {class: "#{css_classes}"}
 end



end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map {|day| content_tag :th, day}.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map {|day| day_cell(day)}.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/gradelevels_helper.rb
module GradelevelsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/badges/_badge.html.erb
<tr id="badgeRow_<%= badge.id%>">
  <td><%= badge.full_name %></td>
  <td><%= badge.programme.name %></td>
  <td><%= badge.gradelevel.name %></td>
  <td><%= badge.start_date %></td>
  <td><%= badge.end_date %></td>
  <td>
    <%= badge.status? ? "#{content_tag(:span, 'Active', class:['badge', 'badge-success'])}".html_safe : "#{content_tag(:span, 'In Active', class:['badge', 'badge-danger'])}".html_safe %>
  </td>
  <td>
    <div class="button-group" role="group" aria-label="Actions">
      <%= link_to "#{content_tag(:i, '', :class => ("fa fa-eye"))}".html_safe, badge, class: "btn btn-primary btn-sm" %>
      <%= link_to "#{content_tag(:i, '', :class => ("fa fa-pencil"))}".html_safe, edit_badge_path(badge), class: "btn btn-warning btn-sm" %>
      <%= link_to "#{content_tag(:i, '', :class => ("fa fa-trash"))}".html_safe, badge_path(badge), method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger btn-sm", remote: true%>
    </div>
  </td>
</tr>

app/views/badges/_form.html.erb
<%= simple_form_for(badge, html: {class: "container"}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.association :programme %>
    <%= f.association :gradelevel %>
    <%= f.input :start_date, as: :string, input_html: {class: "datepicker"} %>
    <%= f.input :end_date, as: :string, input_html: {class: "datepicker"} %>

  <div class="row">
    <div class="col-sm-9 offset-sm-3">
      <%= link_to "Back", send(back_link), class: "btn btn-secondary" %>
      <%= f.button :submit, "#{action_text}", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/badges/edit.html.erb
<%= provide(:page_title, "Edit Badge") %>

<%= render(partial: 'form', locals: {badge: @badge, action_text: "Update", back_link: "badges_path"}) %>

app/views/badges/index.html.erb
<%= provide(:page_title, "Badges") %>

<table class="table table-sm table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Programme</th>
      <th>Gradelevel</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render @badges %>
  </tbody>
</table>
<%= link_to("#{content_tag(:i, ' Add', class: ['fa fa-plus'])}".html_safe, new_badge_path, class: "btn btn-primary btn-sm float-right")%>

app/views/badges/new.html.erb
<%= provide(:page_title, "New Badge") %>

<%= render(partial: 'form', locals: {badge: @badge, action_text: "Create", back_link: "badges_path"}) %>

app/views/badges/show.html.erb
<%= provide(:page_title, "#{@badge.full_name}")%>
<table class="table table-sm table striped">
  <tr>
    <td><strong>Name:</strong></td>
    <td><%= @badge.full_name %></td>
  </tr>

  <tr>
    <td><strong>Programme:</strong></td>
    <td><%= @badge.programme.name %></td>
  </tr>

  <tr>
    <td><strong>Gradelevel:</strong></td>
    <td><%= @badge.gradelevel.name %></td>
  </tr>

  <tr>
    <td><strong>Start date:</strong></td>
    <td><%= @badge.start_date %></td>
  </tr>

  <tr>
    <td><strong>End date:</strong></td>
    <td><%= @badge.end_date %></td>
  </tr>

  <tr>
    <td><strong>Status:</strong></td>
    <td><%= @badge.status? ? "Active" : "In Active" %></td>
  </tr>
  <tr>
    <td><strong>Created By:</strong></td>
    <td>
      <%= @badge.created_by.present? ? User.find_by_id(@badge.created_by).email.humanize : nil %>
      <%= "on #{@badge.created_at.strftime('%d - %m - %y, @ %H: %M: %S') }" %>
    </td>
  </tr>
  <tr>
    <td><strong>Upddated By:</strong></td>
    <td><%= @badge.updated_by.present? ? User.find_by_id(@badge.updated_by).email.humanize : nil %>
       <%= "on #{@badge.updated_at.strftime('%d - %m - %y, @ %H: %M: %S') }" %>
    </td>
  </tr>
</table>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>