config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  devise_for :users

  # resources :staff_categories, only: [:index, :create, :update, :delete, :destroy]
  # resources :staff_departments, only: [:index, :create, :update, :delete, :destroy]

    #School Resouces
    resource :school_infos, only: [:new, :show, :edit, :update, :create, :delete, :destroy], path_names: { new: 'add'}
    resources :gradelevels, :programmes, :classrooms, :periods, :badges

    #Staff Resources
    resources :staff_departments
    resources :staffs do
      member do
        get :contacts
        get :add_contact
        get :edit_contact
        put :update_contact
      end
      collection do
        get :manage
        # put :action
        # post :action
        # delete :action
      end
    end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :programme
  belongs_to :gradelevel

  validates_presence_of :name, :gradelevel_id, :programme_id
  def full_name()
    self.gradelevel.level.to_s + self.name
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord

  validates_presence_of :name, :capacity
end

app/models/gradelevel.rb
class Gradelevel < ApplicationRecord

end

app/models/period.rb
class Period < ApplicationRecord

  def duration
    
  end
end

app/models/programme.rb
class Programme < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
end

app/models/school_info.rb
class SchoolInfo < ApplicationRecord
  mount_uploader :logo, PhotoUploader

  validates_presence_of :name, :code
end

app/models/staff.rb
class Staff < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  belongs_to :staff_department
  has_many :staff_contacts
  has_many :staff_addresses

  accepts_nested_attributes_for :staff_addresses
  accepts_nested_attributes_for :staff_contacts
  # Categories = %w[Academic Non-Academic].freeze

  extend FriendlyId
    friendly_id :first_name, use: :slugged

  def should_generate_new_friendly_id?
    first_name_changed?
  end
  validates_presence_of :first_name, :last_name, :gender, :joining_date, :staff_department_id

  def full_name(title=nil)
    self.title + ' ' + self.last_name + ' ' + self.first_name
  end
end

app/models/staff_address.rb
class StaffAddress < ApplicationRecord
  belongs_to :staff
end

app/models/staff_contact.rb
class StaffContact < ApplicationRecord
  belongs_to :staff
end

app/models/staff_department.rb
class StaffDepartment < ApplicationRecord
  belongs_to :staff_category
  has_many :staffs

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :role
  has_many :staffs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

	 EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\z/i
	 validates_uniqueness_of :email
	 validates_presence_of :email, :password, :role
	 validates_format_of :email, with: EMAIL_REGEX


  def super?
   self.role.name == "super administrator"
  end

  def admin?
   self.role.name == "administrator"
  end

  def teacher?
   self.role.name == "teacher"
  end

  def student?
   self.role.name == "student"
  end

  def guardian?
   self.role.name == "guardian"
  end
end

app/controllers/school_infos_controller.rb
class SchoolInfosController < ApplicationController
  before_action :set_school_info, only: [:show, :edit, :update, :destroy]

  def index
    @school_infos = SchoolInfo.all
  end

  def show
  end

  def new
    @school_info = SchoolInfo.new
  end

  def edit
  end

  def create
    @school_info = SchoolInfo.new(school_info_params)
    @school_info.created_by = current_user.email

    respond_to do |format|
      if @school_info.save
        format.html { redirect_to school_infos_path, notice: 'School info was successfully created.' }
        format.json { render :show, status: :created, location: @school_info }
      else
        format.html { render :new }
        format.json { render json: @school_info.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @school_info.updated_by = current_user.email
      if @school_info.update(school_info_params)
        format.html { redirect_to school_infos_path, notice: 'School info was successfully updated.' }
        format.json { render :show, status: :ok, location: @school_info }
      else
        format.html { render :edit }
        format.json { render json: @school_info.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @school_info.destroy
    respond_to do |format|
      format.html { redirect_to school_infos_url, notice: 'School info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_info
      if SchoolInfo.first.nil?
        @school_info = nil
      else
        @school_info = SchoolInfo.first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_info_params
      params.require(:school_info).permit(:name, :alias, :code, :slogan, :location, :city, :region, :postal_code, :email, :phone, :logo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
   render(partial: "application/error_messages", locals: {object: object})
  end

  def alert_messages(alert)
   render(partial: "application/alert_messages", locals: {msg: alert})
  end

 def notice_messages(notice)
   render(partial: "application/alert_messages", locals: {msg: notice})
 end

 def user_menu(user)
   render(partial: "layouts/menu", locals: {user: user})
 end

 def sortable(column, title=nil)
   title ||= column.titleize
   css_classes = column == sort_column ? "current-column #{sort_direction}" : nil
   direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
   link_to title, params.permit(:sort, :direction, :page, :k).merge(:sort => column, :direction => direction, :page => nil), {class: "#{css_classes}"}
 end



end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map {|day| content_tag :th, day}.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map {|day| day_cell(day)}.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/helpers/school_infos_helper.rb
module SchoolInfosHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/school_infos/_form.html.erb
<%= simple_form_for(school_info, url: school_infos_path, html: {class: "container"}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name %>
    <%= f.input :alias %>
    <%= f.input :code %>
    <%= f.input :slogan %>
    <%= f.input :location %>
    <%= f.input :city %>
    <%= f.input :region %>
    <%= f.input :postal_code %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :logo %>

  <div class="row">
    <div class="col-sm-9 offset-sm-3">
      <%= link_to "Back", send(back_link), class: "btn btn-secondary" %>
      <%= f.button :submit, "#{action_text}", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/school_infos/_school_info.html.erb
<table class="table table-sm table-striped">
  <tr>
    <td><strong>Name:</strong></td>
    <td><%= school_info.name %></td>
  </tr>

  <tr>
    <td><strong>Alias:</strong></td>
    <td><%= school_info.alias %></td>
  </tr>

  <tr>
    <td><strong>Code:</strong></td>
    <td><%= school_info.code %></td>
  </tr>

  <tr>
    <td><strong>Slogan:</strong></td>
    <td><%= school_info.slogan %></td>
  </tr>

  <tr>
    <td><strong>Location:</strong></td>
    <td><%= school_info.location %></td>
  </tr>

  <tr>
    <td><strong>City:</strong></td>
    <td><%= school_info.city %></td>
  </tr>

  <tr>
    <td><strong>Region:</strong></td>
    <td><%= school_info.region %></td>
  </tr>

  <tr>
    <td><strong>Postal code:</strong></td>
    <td><%= school_info.postal_code %></td>
  </tr>

  <tr>
    <td><strong>Email:</strong></td>
    <td><%= school_info.email %></td>
  </tr>

  <tr>
    <td><strong>Phone:</strong></td>
    <td><%= school_info.phone %></td>
  </tr>

  <tr>
    <td><strong>Logo:</strong></td>
    <td><%= school_info.logo %></td>
  </tr>

</table>
<div class="btn-group" role="group" aria-label="SchoolInfoOperations">
  <%= link_to 'Edit Info', edit_school_infos_path, class: "btn btn-warning" %>
  <%= link_to 'Delete', school_infos_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>

app/views/school_infos/edit.html.erb
<%= provide(:page_title, "Edit School Information") %>

<%= render(partial: 'form', locals: {school_info: @school_info, back_link: "school_infos_path", action_text: "Update"}) %>

app/views/school_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>School Infos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Alias</th>
      <th>Code</th>
      <th>Slogan</th>
      <th>Location</th>
      <th>City</th>
      <th>Region</th>
      <th>Postal code</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @school_infos.each do |school_info| %>
      <tr>
        <td><%= school_info.name %></td>
        <td><%= school_info.alias %></td>
        <td><%= school_info.code %></td>
        <td><%= school_info.slogan %></td>
        <td><%= school_info.location %></td>
        <td><%= school_info.city %></td>
        <td><%= school_info.region %></td>
        <td><%= school_info.postal_code %></td>
        <td><%= school_info.email %></td>
        <td><%= school_info.phone %></td>
        <td><%= school_info.logo %></td>
        <td><%= link_to 'Show', school_info %></td>
        <td><%= link_to 'Edit', edit_school_info_path(school_info) %></td>
        <td><%= link_to 'Destroy', school_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School Info', new_school_info_path %>

app/views/school_infos/new.html.erb
<%= provide(:page_title, "Add School Information") %>

<%= render(partial: 'form', locals: {school_info: @school_info, back_link: "school_infos_path", action_text: "Create"}) %>

app/views/school_infos/show.html.erb
<%= provide(:page_title, "School Information")%>

<% if @school_info.nil? %>
  <%= link_to 'Add School Information', new_school_infos_path %>
<% else %>
  <%= render(:partial => 'school_info', locals: {school_info: @school_info})%>
<% end %>